name: twin_forest
description: "나무&열매 성장일기"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # state management, dependency injection, route router_management
  get: ^4.6.6

  url_launcher: ^6.2.4
  card_swiper: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: defaultFont
      fonts:
        - asset: assets/fonts/default_font_light.otf
          weight: 300
        - asset: assets/fonts/default_font_bold.otf
          weight: 500

    - family: nexonGothicFont
      fonts:
        - asset: assets/fonts/nexon_gothic_medium.otf
          weight: 400
        - asset: assets/fonts/nexon_gothic_bold.otf
          weight: 600
        - asset: assets/fonts/nexon_gothic_extra_bold.otf
          weight: 800
    - family: cormorantGaramondFont
      fonts:
        - asset: assets/fonts/CormorantGaramond-Regular.ttf

  assets:
    - assets/images/
    - assets/images/icons/